from .home import HomeViews
from .login import LoginViews
from .logout import LogoutView
from .contact import ContactViews
from .about import AboutViews
from .profile import ProfileViews
from .record import RecordViews
from .settings import SettingsViews
from .manage_scrap import ManageComponentPartViews
from .manage_production import ManageProductionViews
from .manage_defectmode import ManageDefectModeViews
from .manage_user import ManageUserViews
from .report_scrap_monthly import MonthlyComponentPartReportViews
from .auditlog import AuditLogViews