from .home import HomeViews
from .login import LoginViews
from .logout import LogoutView
from .contact import ContactViews
from .about import AboutViews
from .profile import ProfileViews
from .manage_user import ManageUserViews
from .auditlog import AuditLogViews
from .manage_defectmode import ManageDefectModeViews
from .manage_defectmodecategory import ManageDefectModeCategoryViews
from .manage_item_list import ManageItemListViews
from .manage_item_category import ManageItemCategoryViews
from .manage_item_line import ManageItemLineViews
from .manage_bill_of_material import ManageBillOfMaterialViews
from .record import RecordViews
from .manage_scrap import ManageScrapViews
from .manage_line import ManageLineViews
from .dashboard import DashboardViews
from .report_scrap_monthly import MonthlyComponentPartReportViews
from .report_scrap_weight import ScrapWeightReportViews
from .bom_tree import BomTreeViews