from .home import HomeViews
from .login import LoginViews
from .logout import LogoutView
from .contact import ContactViews
from .about import AboutViews
from .profile import ProfileViews
from .record import RecordViews
from .settings import SettingsViews
from .manage_scrap import ManageScrapViews
from .manage_production import ManageProductionViews
from .add_user import AddUserViews
from .manage_user import ManageUserViews