# Generated by Django 6.0.1 on 2026-02-16 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='shift',
            field=models.CharField(choices=[('shift_a', 'กะ A'), ('shift_b', 'กะ B'), ('shift_day', 'กะ Day')], default='shift_day', max_length=20),
        ),
    ]
