# Generated by Django 6.0.5 on 2026-05-08 09:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefectStat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='defect_stats_created', to=settings.AUTH_USER_MODEL)),
                ('defect_mode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='defect_stats', to='core.defectmode')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='defect_stats', to='core.item_list')),
                ('production_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='defect_stats', to='core.line')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['production_line', 'created_at'], name='defstat_line_created_idx'), models.Index(fields=['defect_mode', 'created_at'], name='defstat_defect_created_idx'), models.Index(fields=['part', 'created_at'], name='defstat_part_created_idx')],
            },
        ),
    ]
