# Generated by Django 6.0.1 on 2026-05-19 08:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionDefect',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('qr_work', models.CharField(blank=True, default='', max_length=255)),
                ('result', models.CharField(blank=True, default='', max_length=255)),
                ('scrap_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_defects', to='core.scraprecord')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
