# Generated by Django 6.0.1 on 2026-05-19 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_inspection_defect'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectiondefect',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='inspection_defect_photos/'),
        ),
    ]
