# Generated by Django 6.0.5 on 2026-05-16 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_defectstat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcategory',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='line',
            name='line_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
