# Generated by Django 6.0.1 on 2026-05-19 09:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_inspection_defect_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionDefectImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('image_path', models.TextField(blank=True, default='')),
                ('caption', models.CharField(blank=True, default='', max_length=255)),
                ('order', models.IntegerField(default=0)),
                ('defect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.inspectiondefect')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
