# Generated by Django 6.0.1 on 2026-02-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_scraprecord"),
    ]

    operations = [
        migrations.RenameField(
            model_name="line",
            old_name="process_type",
            new_name="line_process",
        ),
        migrations.RemoveField(
            model_name="billofmaterialitemmater",
            name="scrap_percent",
        ),
        migrations.AddField(
            model_name="billofmaterial",
            name="scrap_percent",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
