# Generated by Django 6.0.2 on 2026-05-22 16:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_inspection_defect_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('machine_no', models.CharField(max_length=255, unique=True)),
                ('machine_name', models.CharField(max_length=255)),
                ('machine_detail', models.TextField(blank=True, null=True)),
                ('res_dept', models.CharField(blank=True, max_length=255)),
                ('responsible1', models.CharField(blank=True, max_length=255)),
                ('responsible2', models.CharField(blank=True, max_length=255)),
                ('is_approved', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MachineLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machine_lines', to='core.line')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machine_lines', to='core.machine')),
            ],
            options={
                'unique_together': {('machine', 'line')},
            },
        ),
        migrations.AddField(
            model_name='machine',
            name='lines',
            field=models.ManyToManyField(blank=True, related_name='machines', through='core.MachineLine', to='core.line'),
        ),
    ]
