# Generated by Django 6.0.5 on 2026-05-25 04:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_department_alter_machine_responsible1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessDefect',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('comment', models.TextField(blank=True, null=True)),
                ('defect_mode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='process_defects', to='core.defectmode')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProcessDefectScrap',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('component_part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='process_defect_scraps', to='core.item_list')),
                ('process_defect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='core.processdefect')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductionRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('products_quantity', models.PositiveIntegerField(default=1)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_records_created', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_records_as_part', to='core.item_list')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_records', to='core.line')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='processdefect',
            name='production_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defects', to='core.productionrecord'),
        ),
    ]
