# Generated by Django 6.0.5 on 2026-05-26 09:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_machine_line_fk_drop_machineline'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailReceiver',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('frequency', models.CharField(choices=[('DAILY', 'ทุกวัน'), ('WEEKLY', 'ทุกสัปดาห์ (จันทร์)'), ('MONTHLY', 'ทุกเดือน (วันที่ 1)')], default='DAILY', max_length=10)),
                ('send_production_report', models.BooleanField(default=True)),
                ('send_inspection_report', models.BooleanField(default=False)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_receivers_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
