# Generated by Django 6.0.7 on 2026-07-08 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_inspectionreport_note"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item_list",
            name="part_number",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="item_list",
            name="sd_code",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=32
            ),
        ),
        migrations.AddIndex(
            model_name="productionrecord",
            index=models.Index(fields=["-created_at"], name="prodrec_created_idx"),
        ),
        migrations.AddIndex(
            model_name="productionrecord",
            index=models.Index(fields=["production_date"], name="prodrec_proddate_idx"),
        ),
        migrations.AddIndex(
            model_name="productionrecord",
            index=models.Index(
                fields=["production_date", "line"], name="prodrec_proddate_line_idx"
            ),
        ),
    ]
