# Generated by Django 6.0.5 on 2026-05-26 11:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_emailreceiver'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manual',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('detail', models.TextField(blank=True, default='')),
                ('usefor', models.CharField(choices=[('ALL', 'ทุกคน (All)'), ('ADMIN', 'ผู้ดูแลระบบ (Admin)'), ('STAFF', 'เจ้าหน้าที่ (Staff)'), ('USER', 'ผู้ใช้งานทั่วไป (User)')], default='ALL', max_length=10)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manuals_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
