# Generated by Django 6.0.5 on 2026-05-27 12:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_detectionobject_defectdetection_kanbanpartmapping_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectMachineMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='object_machine_mappings', to='core.machine')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='machine_mappings', to='core.detectionobject')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
