# Generated by Django 6.0.5 on 2026-05-29 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_objectmachinemapping'),
        ('core', '0013_other_defect_mode'),
    ]

    operations = [
    ]
