# Generated by Django 6.0.1 on 2026-05-29 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_merge_20260529_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionrecord',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='production_records_as_part', to='core.item_list'),
        ),
    ]
