# Generated by Django 6.0.5 on 2026-05-30 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_productionrecord_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionrecord',
            name='lot_number',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
