# Generated by Django 6.0.5 on 2026-06-01 07:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_productionrecord_lot_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kanbanpartmapping',
            name='item',
        ),
        migrations.RemoveField(
            model_name='objectitem',
            name='item',
        ),
        migrations.RemoveField(
            model_name='objectitem',
            name='object',
        ),
        migrations.RemoveField(
            model_name='objectmachinemapping',
            name='machine',
        ),
        migrations.RemoveField(
            model_name='objectmachinemapping',
            name='object',
        ),
        migrations.RemoveField(
            model_name='detectionobject',
            name='model_path',
        ),
        migrations.RemoveField(
            model_name='detectionobject',
            name='object_detection_model',
        ),
        migrations.RemoveField(
            model_name='detectionobject',
            name='quantity',
        ),
        migrations.CreateModel(
            name='DefectDetectionInModels',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('defect_mode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='defect_detection_models', to='core.defectmode')),
                ('inspection_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='defect_detection_models', to='core.inspectionmodels')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='defect_detection_models', to='core.detectionobject')),
            ],
            options={
                'unique_together': {('object', 'defect_mode', 'inspection_model')},
            },
        ),
        migrations.CreateModel(
            name='ItemObject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='item_objects', to='core.item_list')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='item_objects', to='core.detectionobject')),
            ],
            options={
                'unique_together': {('item', 'object')},
            },
        ),
        migrations.CreateModel(
            name='KanbanItemMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('kanban_qr', models.CharField(max_length=255, unique=True)),
                ('item_qr', models.CharField(max_length=255)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kanban_item_mappings', to='core.item_list')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MachineObject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='machine_objects', to='core.machine')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='machine_objects', to='core.detectionobject')),
            ],
            options={
                'unique_together': {('machine', 'object')},
            },
        ),
        migrations.CreateModel(
            name='ObjectDetectionModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('inspection_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='object_detection_models', to='core.inspectionmodels')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='object_detection_models', to='core.detectionobject')),
            ],
            options={
                'unique_together': {('object', 'inspection_model')},
            },
        ),
        migrations.DeleteModel(
            name='DefectDetection',
        ),
        migrations.DeleteModel(
            name='KanbanPartMapping',
        ),
        migrations.DeleteModel(
            name='ObjectItem',
        ),
        migrations.DeleteModel(
            name='ObjectMachineMapping',
        ),
    ]
