# Generated by Django 6.0.5 on 2026-06-01 08:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_kanbanpartmapping_item_remove_objectitem_item_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('display_number', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_number', 'name'],
            },
        ),
        migrations.AddField(
            model_name='productionrecord',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='production_records', to='core.shift'),
        ),
    ]
