# Generated by Django 6.0.5 on 2026-06-01 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_seed_shifts'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionrecord',
            name='production_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productionrecord',
            name='lot_number',
            field=models.CharField(blank=True, db_index=True, max_length=80, null=True),
        ),
    ]
