# Generated by Django 6.0.5 on 2026-06-02 09:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_contactmessage_partrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostCenter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'cost_centers',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('code', models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True)),
                ('short_name', models.CharField(blank=True, max_length=10)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('name_en', models.CharField(blank=True, max_length=200)),
                ('name_ja', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('description_ja', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'divisions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('title_th', models.CharField(blank=True, max_length=100)),
                ('title_en', models.CharField(blank=True, max_length=100)),
                ('title_ja', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('description_ja', models.TextField(blank=True)),
                ('is_system_role', models.BooleanField(default=False)),
                ('level', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'employee_roles',
                'ordering': ['-level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EmployType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'employ_types',
            },
        ),
        migrations.CreateModel(
            name='JobLevel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'job_levels',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('short_name', models.CharField(blank=True, max_length=10)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('name_en', models.CharField(blank=True, max_length=200)),
                ('name_ja', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('description_ja', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'positions',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='department',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='department',
            name='description_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='department',
            name='description_ja',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='department',
            name='name_en',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='department',
            name='name_ja',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='department',
            name='short_name',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='telephone_number',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='user',
            name='totp_backup_codes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='user',
            name='totp_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='totp_secret',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='country_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='occupation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='timezone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='department',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='departments', to='core.division'),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('emp_code', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(blank=True, max_length=50)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('title_en', models.CharField(blank=True, max_length=50)),
                ('first_name_en', models.CharField(blank=True, max_length=150)),
                ('last_name_en', models.CharField(blank=True, max_length=150)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('cost_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='core.costcenter')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='employee', to=settings.AUTH_USER_MODEL)),
                ('employ_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='core.employtype')),
                ('job_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='core.joblevel')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='core.position')),
            ],
            options={
                'db_table': 'employees',
                'ordering': ['emp_code'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='employee_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='core.employeerole'),
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('code', models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True)),
                ('short_name', models.CharField(blank=True, max_length=10)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('name_en', models.CharField(blank=True, max_length=200)),
                ('name_ja', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('description_ja', models.TextField(blank=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='organizations', to='core.department')),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='organizations', to='core.division')),
            ],
            options={
                'db_table': 'organizations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationEmployee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('shift', models.CharField(choices=[('A', 'Shift A'), ('B', 'Shift B'), ('Day', 'Shift Day')], max_length=10)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_assignments', to='core.employee')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organization_employees', to='core.organization')),
            ],
            options={
                'db_table': 'organization_employees',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('code', models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True)),
                ('short_name', models.CharField(blank=True, max_length=10)),
                ('name', models.CharField(max_length=200)),
                ('name_en', models.CharField(blank=True, max_length=200)),
                ('name_ja', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('description_ja', models.TextField(blank=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sections', to='core.department')),
            ],
            options={
                'db_table': 'sections',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='organization',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='organizations', to='core.section'),
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('round_number', models.PositiveSmallIntegerField(choices=[(1, 'Round 1'), (2, 'Round 2')])),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('duration_days', models.PositiveIntegerField(default=0, editable=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('extended', 'Extended'), ('completed', 'Completed'), ('terminated', 'Terminated')], default='active', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='core.employee')),
                ('renewed_as', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_contract', to='core.employee')),
            ],
            options={
                'db_table': 'contracts',
                'ordering': ['employee', 'round_number'],
                'unique_together': {('employee', 'round_number')},
            },
        ),
    ]
