# Generated by Django 6.0.5 on 2026-06-04 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_costcenter_division_employeerole_employtype_joblevel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionmodels',
            name='model_type',
            field=models.CharField(choices=[('OBJECT', 'Object Detection'), ('DEFECT', 'Defect Detection')], default='OBJECT', max_length=10),
        ),
    ]
