# Generated by Django 6.0.5 on 2026-06-05 04:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_machineobject_camera_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionNGLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('kanban_qr', models.CharField(max_length=255)),
                ('item_qr', models.CharField(max_length=255)),
                ('photo_path', models.TextField(blank=True, null=True)),
                ('inspected_at', models.DateTimeField(db_index=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ng_logs', to='core.item_list')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ng_logs', to='core.machine')),
            ],
            options={
                'ordering': ['-inspected_at'],
            },
        ),
        migrations.CreateModel(
            name='InspectionNGLogDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('camera_number', models.PositiveSmallIntegerField()),
                ('object_found', models.BooleanField()),
                ('object_count', models.PositiveIntegerField()),
                ('expected_count', models.PositiveIntegerField()),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('photo_path', models.TextField(blank=True, null=True)),
                ('defect_mode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ng_log_details', to='core.defectmode')),
                ('detection_object', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ng_log_details', to='core.detectionobject')),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='core.inspectionnglog')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InspectionOKLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('kanban_qr', models.CharField(max_length=255)),
                ('item_qr', models.CharField(max_length=255)),
                ('photo_path', models.TextField(blank=True, null=True)),
                ('inspected_at', models.DateTimeField(db_index=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ok_logs', to='core.item_list')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ok_logs', to='core.machine')),
            ],
            options={
                'ordering': ['-inspected_at'],
            },
        ),
        migrations.CreateModel(
            name='InspectionOKLogDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('camera_number', models.PositiveSmallIntegerField()),
                ('object_found', models.BooleanField()),
                ('object_count', models.PositiveIntegerField()),
                ('expected_count', models.PositiveIntegerField()),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('photo_path', models.TextField(blank=True, null=True)),
                ('detection_object', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ok_log_details', to='core.detectionobject')),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='core.inspectionoklog')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='inspectionnglog',
            index=models.Index(fields=['machine', 'inspected_at'], name='core_inspec_machine_ebc6c2_idx'),
        ),
        migrations.AddIndex(
            model_name='inspectionnglog',
            index=models.Index(fields=['item', 'inspected_at'], name='core_inspec_item_id_e68504_idx'),
        ),
        migrations.AddIndex(
            model_name='inspectionnglog',
            index=models.Index(fields=['kanban_qr'], name='core_inspec_kanban__ac8ed3_idx'),
        ),
        migrations.AddIndex(
            model_name='inspectionoklog',
            index=models.Index(fields=['machine', 'inspected_at'], name='core_inspec_machine_91af7d_idx'),
        ),
        migrations.AddIndex(
            model_name='inspectionoklog',
            index=models.Index(fields=['item', 'inspected_at'], name='core_inspec_item_id_1588b5_idx'),
        ),
        migrations.AddIndex(
            model_name='inspectionoklog',
            index=models.Index(fields=['kanban_qr'], name='core_inspec_kanban__9fe5ce_idx'),
        ),
    ]
