# Generated by Django 5.1.14 on 2026-06-22 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_canonical_shift_ids"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scraprecord",
            name="created_by",
        ),
        migrations.AddField(
            model_name="scraprecord",
            name="machine",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="scrap_records",
                to="core.machine",
            ),
        ),
        migrations.AlterField(
            model_name="auditlogentry",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
